# Generated by Django 4.2.8 on 2023-12-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='Default email', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='default message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Default subject', max_length=255),
        ),
    ]
